name: Release

permissions:
  contents: write

on:
  release:
    types: [ created ]

jobs:
  build-native:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1.0.1
        name: Run tests
        with:
          command: test
      - uses: actions-rs/cargo@v1.0.1
        name: Build
        with:
          command: build
          args: --release --all-features
      - name: Rename Release (Unix)
        run: |
          cargo install default-target
          mkdir assets
          FILENAME=spacing-calculator-${{github.event.release.tag_name}}-$(default-target)
          mv target/release/spacing-calculator assets
          cd assets
          tar --format=ustar -czf $FILENAME.tar.gz spacing-calculator
          rm spacing-calculator
          ls .
        if: ${{ matrix.platform != 'windows-latest' }}
        shell: bash
      - name: Rename Release (Windows)
        run: |
          cargo install default-target
          mkdir assets
          FILENAME=spacing-calculator-${{github.event.release.tag_name}}-$(default-target)
          mv target/release/spacing-calculator.exe assets/spacing-calculator.exe
          cd assets
          powershell Compress-Archive -Path * -Destination ${FILENAME}.zip
          rm spacing-calculator.exe
          ls .
        if: ${{ matrix.platform == 'windows-latest' }}
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: assets/*
  build-non-native:
    strategy:
      fail-fast: false
      matrix:
        target: [ "aarch64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf", "x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1.0.1
        name: Run tests
        with:
          command: test
          use-cross: true
          args: --target ${{matrix.target}}
      - uses: actions-rs/cargo@v1.0.1
        name: Build
        with:
          command: build
          use-cross: true
          args: --release --all-features --target ${{matrix.target}}
      - name: Rename Release
        run: |
          mkdir assets
          FILENAME=spacing-calculator-${{github.event.release.tag_name}}-${{matrix.target}}
          mv target/${{matrix.target}}/release/spacing-calculator assets
          cd assets
          tar --format=ustar -czf $FILENAME.tar.gz spacing-calculator
          rm spacing-calculator
          ls .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: assets/*